name: CREATE Docker image and EC2

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t myapp:latest .

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <YOUR-ROLE-ARN>
          aws-region: us-east-1

      - run: terraform init
      - run: terraform plan

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <YOUR-ROLE-ARN>
          aws-region: us-east-1

      - run: terraform init
      - run: terraform apply -auto-approve
